# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the b16 branch
  push:
    branches: [ b16 ]
  pull_request:
    branches: [ b16 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_mine:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1 # windows

      # Runs a single command using the runners shell
     # - name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: |
        #  echo Add other actions to build,
         # echo test, and deploy your project.

      #- name: ls # works
        #run: ls
        
      - name: folder_attempt
        run: |
          cl /EHsc Prime.cpp main.cpp


      - name: 'Upload Artifact' # ??  >> it became a programm
        uses: actions/upload-artifact@v2
        with:
          name: prime-artifact
          path: "*.exe" # to download like exe
          retention-days: 2 # durance of storage 
          
          
  telegram:
      needs: build_mine
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@master
        - uses: ilammy/msvc-dev-cmd@v1 # windows


        - name: send custom message with args
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO_DEBUG }}
            token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
            args: ${{ GITHUB_ACTOR }} YAY.
            #args: The ${{ github.event_name }} event triggered first step YAY.
            # message: pss, kisik
            
        - name: download
          uses: actions/download-artifact@v2
          with: 
            name: prime-artifact
            
 
    
      
